// gestionProductosStyles.js
export const styles = {
  pageContainer: {
    minHeight: "100vh",
    backgroundColor: "#f8f9fa",
    padding: "1.5rem",
  },
  container: {
    maxWidth: "1400px",
    margin: "0 auto",
    backgroundColor: "#ffffff",
    borderRadius: "8px",
    boxShadow: "0 2px 10px rgba(0, 0, 0, 0.1)",
    overflow: "hidden",
  },
  header: {
    background: "#1a2332",
    padding: "1.5rem 2rem",
    color: "white",
    borderBottom: "1px solid rgba(255, 255, 255, 0.1)",
  },
  headerContent: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    flexWrap: "wrap",
    gap: "1rem",
  },
  title: {
    fontSize: "1.75rem",
    fontWeight: "600",
    margin: "0",
    color: "#ffffff",
  },
  subtitle: {
    fontSize: "0.95rem",
    opacity: "0.8",
    margin: "0.5rem 0 0 0",
    color: "#e2e8f0",
  },
  addButton: {
    padding: "0.75rem 1.5rem",
    borderRadius: "4px",
    backgroundColor: "#3498db",
    color: "white",
    cursor: "pointer",
    transition: "all 0.2s ease",
    fontWeight: "500",
    fontSize: "0.95rem",
    border: "none",
  },
  content: {
    padding: "2rem",
  },
  controlsContainer: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "2rem",
    flexWrap: "wrap",
    gap: "1rem",
  },
  searchContainer: {
    display: "flex",
    gap: "1rem",
    alignItems: "center",
    flexWrap: "wrap",
  },
  searchInput: {
    padding: "0.6rem 1rem",
    border: "1px solid #e2e8f0",
    borderRadius: "4px",
    fontSize: "0.95rem",
    minWidth: "250px",
  },
  filterSelect: {
    padding: "0.6rem 1rem",
    border: "1px solid #e2e8f0",
    borderRadius: "4px",
    fontSize: "0.95rem",
    backgroundColor: "white",
    minWidth: "200px",
  },
  tableContainer: {
    overflowX: "auto",
    border: "1px solid #e2e8f0",
    borderRadius: "4px",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    backgroundColor: "white",
  },
  tableHeader: {
    backgroundColor: "#f8f9fa",
    borderBottom: "1px solid #e2e8f0",
  },
  tableHeaderCell: {
    padding: "1rem",
    textAlign: "left",
    fontWeight: "600",
    color: "#1a2332",
    fontSize: "0.9rem",
    borderRight: "1px solid #e2e8f0",
  },
  tableRow: {
    borderBottom: "1px solid #f1f3f4",
    transition: "background-color 0.2s ease",
  },
  tableCell: {
    padding: "1rem",
    borderRight: "1px solid #f1f3f4",
    fontSize: "0.9rem",
    color: "#374151",
    whiteSpace: "normal",
  },
  productImage: {
    width: "50px",
    height: "50px",
    objectFit: "cover",
    borderRadius: "4px",
    border: "1px solid #e2e8f0",
  },
  productName: {
    fontWeight: "600",
    color: "#1a2332",
    marginBottom: "0.25rem",
  },
  productDescription: {
    color: "#64748b",
    fontSize: "0.85rem",
  },
  badge: {
    padding: "0.25rem 0.75rem",
    borderRadius: "4px",
    fontSize: "0.8rem",
    fontWeight: "500",
    backgroundColor: "#e2e8f0",
    color: "#1a2332",
  },
  sizeBadge: {
    padding: "0.2rem 0.5rem",
    borderRadius: "3px",
    fontSize: "0.7rem",
    fontWeight: "500",
    backgroundColor: "#3498db",
    color: "white",
    margin: "0.1rem",
    display: "inline-block",
  },
  actionsContainer: {
    display: "flex",
    gap: "0.5rem",
  },
  actionButton: {
    padding: "0.4rem 0.75rem",
    borderRadius: "4px",
    border: "none",
    cursor: "pointer",
    fontSize: "0.8rem",
    fontWeight: "500",
    transition: "all 0.2s ease",
  },
  editButton: {
    backgroundColor: "#3498db",
    color: "white",
  },
  deleteButton: {
    backgroundColor: "#e74c3c",
    color: "white",
  },
  viewButton: {
    backgroundColor: "#2ecc71",
    color: "white",
  },
  modalOverlay: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1000,
  },
  modalContent: {
    backgroundColor: "white",
    borderRadius: "6px",
    width: "90%",
    maxWidth: "800px",
    maxHeight: "90vh",
    overflow: "auto",
    boxShadow: "0 10px 25px -5px rgba(0, 0, 0, 0.2)",
  },
  modalHeader: {
    padding: "1rem 1.5rem",
    borderBottom: "1px solid #e2e8f0",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#1a2332",
    color: "white",
  },
  modalTitle: {
    margin: 0,
    fontSize: "1.1rem",
    fontWeight: "600",
  },
  modalBody: {
    padding: "1.5rem",
  },
  formGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: "1rem",
  },
  formGroup: {
    marginBottom: "1rem",
  },
  label: {
    display: "block",
    marginBottom: "0.35rem",
    fontWeight: "500",
    color: "#1a2332",
    fontSize: "0.85rem",
  },
  input: {
    width: "100%",
    padding: "0.6rem 0.75rem",
    border: "1px solid #e2e8f0",
    borderRadius: "4px",
    fontSize: "0.9rem",
    transition: "all 0.2s ease-in-out",
    backgroundColor: "#ffffff",
    boxSizing: "border-box",
  },
  textarea: {
    width: "100%",
    padding: "0.6rem 0.75rem",
    border: "1px solid #e2e8f0",
    borderRadius: "4px",
    minHeight: "100px",
    fontSize: "0.9rem",
    resize: "vertical",
    transition: "all 0.2s ease-in-out",
    backgroundColor: "#ffffff",
    fontFamily: "inherit",
    boxSizing: "border-box",
  },
  select: {
    width: "100%",
    padding: "0.6rem 0.75rem",
    border: "1px solid #e2e8f0",
    borderRadius: "4px",
    fontSize: "0.9rem",
    backgroundColor: "#ffffff",
    cursor: "pointer",
    transition: "all 0.2s ease-in-out",
    boxSizing: "border-box",
  },
  imageUploadArea: {
    border: "1px dashed #cbd5e1",
    borderRadius: "4px",
    padding: "1rem",
    textAlign: "center",
    transition: "all 0.2s ease-in-out",
    backgroundColor: "#f8fafc",
    cursor: "pointer",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    height: "100px",
  },
  fileInput: {
    display: "none",
  },
  uploadText: {
    color: "#475569",
    fontSize: "0.9rem",
    marginBottom: "0.25rem",
  },
  uploadSubtext: {
    color: "#94a3b8",
    fontSize: "0.8rem",
  },
  previewContainer: {
    marginTop: "0.75rem",
    textAlign: "center",
  },
  previewImage: {
    maxWidth: "150px",
    maxHeight: "150px",
    borderRadius: "4px",
    objectFit: "cover",
    border: "1px solid #e2e8f0",
  },
  tallasSection: {
    gridColumn: "1 / -1",
    marginTop: "0.5rem",
  },
  tallasContainer: {
    display: "flex",
    flexDirection: "column",
    gap: "1rem",
    marginTop: "0.5rem",
  },
  genderGroup: {
    backgroundColor: "#f8fafc",
    borderRadius: "4px",
    padding: "1rem",
    border: "1px solid #e2e8f0",
  },
  genderTitle: {
    marginBottom: "0.75rem",
    color: "#1a2332",
    fontSize: "0.9rem",
    fontWeight: "600",
  },
  sizesGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(100px, 1fr))",
    gap: "0.5rem",
  },
  tallaCheckbox: {
    display: "flex",
    alignItems: "center",
    gap: "0.4rem",
    padding: "0.4rem 0.6rem",
    backgroundColor: "#ffffff",
    borderRadius: "4px",
    cursor: "pointer",
    transition: "all 0.2s ease-in-out",
    border: "1px solid #e2e8f0",
    fontSize: "0.8rem",
    fontWeight: "500",
  },
  tallaCheckboxSelected: {
    backgroundColor: "#3498db",
    borderColor: "#3498db",
    color: "#ffffff",
  },
  checkbox: {
    width: "16px",
    height: "16px",
    cursor: "pointer",
    accentColor: "#3498db",
  },
  submitButton: {
    backgroundColor: "#3498db",
    color: "white",
    padding: "0.75rem 1.5rem",
    border: "none",
    borderRadius: "4px",
    cursor: "pointer",
    fontSize: "1rem",
    fontWeight: "600",
    width: "100%",
    marginTop: "1.5rem",
    transition: "all 0.2s ease-in-out",
  },
  submitButtonDisabled: {
    backgroundColor: "#94a3b8",
    cursor: "not-allowed",
  },
  error: {
    color: "#e74c3c",
    backgroundColor: "#fef2f2",
    border: "1px solid #fecaca",
    padding: "0.75rem 1rem",
    borderRadius: "4px",
    textAlign: "center",
    fontSize: "0.9rem",
    marginBottom: "1.5rem",
  },
  progressContainer: {
    marginTop: "1.5rem",
  },
  progressBar: {
    width: "100%",
    height: "6px",
    backgroundColor: "#e2e8f0",
    borderRadius: "3px",
    overflow: "hidden",
    marginBottom: "0.5rem",
  },
  progressBarFill: {
    height: "100%",
    borderRadius: "3px",
    backgroundColor: "#3498db",
    width: "0%",
    transition: "width 0.3s ease",
  },
  progressText: {
    textAlign: "center",
    fontSize: "0.85rem",
    color: "#64748b",
    fontWeight: "500",
  },
  requiredField: {
    color: "#e74c3c",
    marginLeft: "4px",
  },
  helpText: {
    fontSize: "0.85rem",
    color: "#64748b",
    marginTop: "0.5rem",
  },
  emptyState: {
    textAlign: "center",
    padding: "3rem 2rem",
    color: "#64748b",
  },
  emptyStateText: {
    fontSize: "1.1rem",
    fontWeight: "600",
    marginBottom: "0.5rem",
    color: "#1a2332",
  },
  emptyStateSubtext: {
    fontSize: "0.95rem",
    color: "#64748b",
  },
  modalCloseButton: {
    background: "none",
    border: "none",
    color: "white",
    fontSize: "1.5rem",
    cursor: "pointer",
    padding: "0.5rem",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
};